/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clientui;

import java.rmi.RemoteException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Kris
 */
public class ServicePanel extends javax.swing.JPanel {
    
    private BankCardClient mainLogic;
    /**
     * Creates new form ServicePanel
     */
    public ServicePanel(BankCardClient mainLogic) {
        this.mainLogic = mainLogic;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCardNumber = new javax.swing.JLabel();
        txtCardNumber = new javax.swing.JTextField();
        lblCardError = new javax.swing.JLabel();
        btnTokenize = new javax.swing.JButton();
        lblFirstResult = new javax.swing.JLabel();
        txtTokenResult = new javax.swing.JTextField();
        lblToken = new javax.swing.JLabel();
        txtToken = new javax.swing.JTextField();
        lblTokenError = new javax.swing.JLabel();
        btnDetokenize = new javax.swing.JButton();
        lblSecondResult = new javax.swing.JLabel();
        txtCardResult = new javax.swing.JTextField();
        lblMessage = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();

        lblCardNumber.setText("Card Number:");

        txtCardNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCardNumberActionPerformed(evt);
            }
        });

        lblCardError.setForeground(new java.awt.Color(255, 51, 51));

        btnTokenize.setText("Tokenize");
        btnTokenize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTokenizeActionPerformed(evt);
            }
        });

        lblFirstResult.setText("Result:");

        lblToken.setText("Token:");

        txtToken.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTokenActionPerformed(evt);
            }
        });

        lblTokenError.setForeground(new java.awt.Color(255, 51, 51));

        btnDetokenize.setText("Detokenize");
        btnDetokenize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetokenizeActionPerformed(evt);
            }
        });

        lblSecondResult.setText("Result:");

        lblMessage.setForeground(new java.awt.Color(255, 51, 51));

        btnLogout.setText("Log out");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblCardNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCardNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblCardError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(btnTokenize)
                        .addGap(25, 25, 25)
                        .addComponent(lblFirstResult, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTokenResult))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblToken, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtToken, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblTokenError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(btnDetokenize)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblSecondResult, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(txtCardResult)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCardNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCardNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCardError))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTokenize)
                    .addComponent(lblFirstResult)
                    .addComponent(txtTokenResult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblToken)
                    .addComponent(txtToken, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTokenError))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnDetokenize)
                        .addComponent(lblSecondResult))
                    .addComponent(txtCardResult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLogout, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE))
                .addContainerGap(36, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtCardNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCardNumberActionPerformed
        String text = txtCardNumber.getText();
        if(!text.matches("\\d{16}")) {
            lblCardError.setText("Wrong format! Card number must be 16-digit number!");
        } else {
            lblCardError.setText("");
        }
    }//GEN-LAST:event_txtCardNumberActionPerformed

    private void txtTokenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTokenActionPerformed
        String text = txtToken.getText();
        if(!text.matches("\\d{16}")) {
            lblTokenError.setText("Wrong format! Token must be 16-digit number!");
        } else {
            lblTokenError.setText("");
        }
    }//GEN-LAST:event_txtTokenActionPerformed

    private void btnTokenizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTokenizeActionPerformed
        String cardNumber = txtCardNumber.getText();
        try {
            String token =  mainLogic.getServer().tokenize(mainLogic.getSessionInfo(), cardNumber);
            if(!token.startsWith("Error")) {
                txtTokenResult.setText(token);
                lblMessage.setText("Token successfully registered!");
            } else {
                lblMessage.setText("Unable to tokenize! Invalid information or insufficient privilege level");
            }
        } catch (RemoteException ex) {
            Logger.getLogger(ServicePanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnTokenizeActionPerformed

    private void btnDetokenizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetokenizeActionPerformed
        String token = txtToken.getText();
        try {
            String cardNumber =  mainLogic.getServer().detokenize(mainLogic.getSessionInfo(), token);
            if(cardNumber != null) {
                txtCardResult.setText(cardNumber);
                lblMessage.setText("Successful detokenization!");
            } else {
                lblMessage.setText("Unable to detokenize! Incorrect token or insufficient privilege level");
            }
        } catch (RemoteException ex) {
            Logger.getLogger(ServicePanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnDetokenizeActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        try {
            mainLogic.getServer().closeConnection(mainLogic.getSessionInfo());
            mainLogic.changeSession(null);
        } catch (RemoteException ex) {
            Logger.getLogger(ServicePanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnLogoutActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDetokenize;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnTokenize;
    private javax.swing.JLabel lblCardError;
    private javax.swing.JLabel lblCardNumber;
    private javax.swing.JLabel lblFirstResult;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JLabel lblSecondResult;
    private javax.swing.JLabel lblToken;
    private javax.swing.JLabel lblTokenError;
    private javax.swing.JTextField txtCardNumber;
    private javax.swing.JTextField txtCardResult;
    private javax.swing.JTextField txtToken;
    private javax.swing.JTextField txtTokenResult;
    // End of variables declaration//GEN-END:variables
}
